name: 'Stage'
description: 'Stage build'
inputs:
  finished:
    description: If a previous stage already finished the build, the stage will set all output variables to the input ones and exit
    required: true
  from_artifact:
    description: If a previous stage already uploaded build artifacts, the stage will resume building
    required: true
  x86:
    description: Build x86 binary
    required: false
    default: 'false'
  arm:
    description: Build arm binary
    required: false
    default: 'false'
  simd:
    description: SIMD variant to build (sse3, avx, avx2, avx512)
    required: false
    default: 'sse3'
  artifact_id:
    description: Specific artifact ID to resume from (overrides auto-detection)
    required: false
    default: ''
outputs:
  finished:
    description: If a previous stage already finished the build, the stage will set all output variables to the input ones and exit
  artifact_id:
    description: The artifact ID that was uploaded (for manual resume)
runs:
  using: 'node20'
  main: 'index.js'